export const portfolioImages = [
    {
        id: '1',
        src: '/images/portfolio-img-1.png',
        alt: '',
        width: 200,
        height: 200,
    },
    {
        id: '2',
        src: '/images/portfolio-img-2.png',
        alt: '',
        width: 200,
        height: 200,
    },
    {
        id: '3',
        src: '/images/portfolio-img-3.png',
        alt: '',
        width: 200,
        height: 200,
    },
    {
        id: '4',
        src: '/images/portfolio-img-4.png',
        alt: '',
        width: 200,
        height: 200,
    },
    {
        id: '5',
        src: '/images/portfolio-img-5.png',
        alt: '',
        width: 200,
        height: 200,
    },
    {
        id: '6',
        src: '/images/portfolio-img-6.png',
        alt: '',
        width: 200,
        height: 200,
    },
    {
        id: '7',
        src: '/images/portfolio-img-7.png',
        alt: '',
        width: 200,
        height: 200,
    },
    {
        id: '8',
        src: '/images/portfolio-img-8.png',
        alt: '',
        width: 200,
        height: 200,
    },
    {
        id: '9',
        src: '/images/portfolio-img-9.png',
        alt: '',
        width: 200,
        height: 200,
    },
    {
        id: '10',
        src: '/images/portfolio-img-10.png',
        alt: '',
        width: 200,
        height: 200,
    },
  {
        id: '11',
        src: '/images/portfolio-img-11.png',
        alt: '',
        width: 200,
        height: 200,
    },  
    {
        id: '12',
        src: '/images/portfolio-img-12.png',
        alt: '',
        width: 200,
        height: 200,
    },] 
        